### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by MinerMinerMods** [fastnlight0/Python-Programs#2]
Auto adjustment for the autopaster
```python
import os
#Setup
String command = "ctrl"
if platform.system() == "Darwin":
    #MacOS code
    command = "command"
else
    #Non-MacOS code
    command = "ctrl"
#Additional Code
pyautogui.hotkey(command, 'v')
```
This allows a download and play experience out of the box and allows you to remove a comment

**Comment by fastnlight0** [comment]
Generally, suggesting code changes should be pull requests, not issues. However, I have made an improvement with the code that makes it run a lot faster (switching to pynput as opposed to pyautogui). I'll commit these new changes, and merge yours
